# Generated by Django 5.0.3 on 2024-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="advertisements/"),
        ),
    ]
