# Generated by Django 5.0.3 on 2024-12-13 16:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_advertisement_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="advertisements/",
            ),
        ),
    ]
