# Generated by Django 5.0.3 on 2024-12-20 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_advertisement_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_advertisements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_advertisements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
